language: android

sudo: false

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

env:
  global:
  - ANDROID_API=28
  - ANDROID_BUILD_TOOLS=27.0.3
  - ADB_INSTALL_TIMEOUT=5

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
  - android-sdk-preview-license-.+

before_install:
- openssl aes-256-cbc -K $encrypted_9503677af408_key -iv $encrypted_9503677af408_iv
  -in my.jks.enc -out my.jks -d
- yes | sdkmanager "platforms;android-28"

before_script:
- chmod +x gradlew

script:
- "./gradlew assembleRelease"

before_deploy:
- ls app/build/outputs/apk/release
- mv app/build/outputs/apk/app-release.apk

deploy:
  provider: releases
  api_key:
    secure: 4973f50485c4955b85c7ca221fb6acfe91f7182c
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
