language: android

notifications:
  email: false

sudo: false

android:
  components:
    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    - extra-android-support

before_install:
 - chmod +x gradlew

 script:
   - ./gradlew assembleRelease
